version: '3'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      - redis