version: "3.4"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  eureka-server:
#    build: ./eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - one-net

#  config-server:
#    build: ./config-server
#    depends_on:
#      - eureka-server
#    ports:
#      - "8888:8888"
#    networks:
#      - one-net

#  greeting-service:
#    build: ./greeting-service
#    depends_on:
#      - eureka-server
#      - config-server
#    ports:
#      - "8080:8080"
#    networks:
#      - one-net

#  spring-kafka:
#      build: ./spring-kafka
#      depends_on:
#        - eureka-server
#        - config-server
#        - kafka
#        - zookeeper
#      ports:
#        - "8081:8081"
#      networks:
#        - one-net
networks:
    one-net:

#docker run -p 8000:8000 -p 8088:8088 -e "SPLUNK_PASSWORD=J2u3n4i5o6r7@a" -e "SPLUNK_START_ARGS=--accept-license" -it splunk/splunk:latest
#docker network create --driver bridge --attachable skynet
#docker run --network skynet --name so1 --hostname so1 -p 8000:8000 -e "SPLUNK_PASSWORD=<password>" -e "SPLUNK_START_ARGS=--accept-license" -it splunk/splunk:latest