apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-kafka
  name: spring-kafka
  namespace: kafka
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-kafka
  type: LoadBalancer
# kubectl apply -f 07-service.yaml