server:
  port: 8000
spring:
  application:
    name: consulting-service
  datasource:
    url: jdbc:mysql://localhost:3306/consulting_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: consulting_service
    user: root
    password: root