package estructural.composite;

public enum MarcaEletronicos {
    DELL, HP, ACER, ASUS, LENOVO, APPLE, SAMSUNG, LG, POSITIVO, VAIO, MICROSOFT, XIAOMI, RAZER, ALIENWARE, AVELL, COMPAQ, CCE, IBM, ITAUTEC, MIRAX, NEOX, PHILCO, SEMP_TOSHIBA, SONY, TOSHIBA, OUTROS
}
