version: '3.7'

services:

  db:
    image: mysql/mysql-server:latest
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - proxy


networks:
  proxy:
    driver: bridge

volumes:
  setup:
  elasticsearch:
  portainer_data:
    driver: local
  jenkins-data:
    driver: local  
