apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-kafka
  name: spring-kafka
  namespace: aincrad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: spring-kafka
    spec:
      containers:
      - image: juniomenchik/spring-kafka:0.0.1
        name: spring-kafka
        resources: {}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 10" ]
# kubectl apply -f 06-deployment.yaml