spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: prod
      name: ${spring.application.name}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka