spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
      name: ${spring.application.name}

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false