spring:
  application:
    name: cambio-service

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service_dev?useTimezone=true&serverTimezone=UTC
    username: cambio_service_user
    password: userpassword
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio_service_dev
    user: cambio_service_user
    password: userpassword

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
