networks:
  proxy:
    driver: bridge

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy

  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'example_user'
      MYSQL_PASSWORD: 'userpassword'
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - proxy

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy

  adminer:
    image: adminer
    restart: always
    ports:
      - 9002:8080
    networks:
      - proxy

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    privileged: true
    hostname: jenkinsserver
    user: root
    labels:
      jenkins.aincrad.com.br: "Jenkins-Server by JeffMenchik.dev"
    ports:
      - "9001:8080"
      - "50000:50000"
    networks:
      - proxy
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:
    driver: local
  jenkins-data:
    driver: local
